targets:
  $default:
    builders:
      rdf_vocabulary_builder|vocabulary_builder:
        enabled: true
        options:
          manifest_asset_path: "lib/src/vocab/manifest.json"
          output_dir: "lib/src/vocab/generated"

builders:
  vocabulary_builder:
    import: "package:rdf_vocabulary_builder/vocab_builder.dart"
    builder_factories: ["vocabularyBuilder"]
    build_extensions: {
      ".vocab_manifest.json": ["{{}}/generated/_index.dart", "{{}}/generated/*.dart"],
    }
    build_to: source
    auto_apply: dependents