targets:
  $default:
    builders:
      rdf_vocab_builder|vocabulary_builder:
        enabled: true
        options:
          manifest_asset_path: "lib/src/vocab/manifest.json"
          output_dir: "lib/src/vocab/generated"

builders:
  vocabulary_builder:
    import: "package:rdf_vocab_builder/vocab_builder.dart"
    builder_factories: ["vocabularyBuilder"]
    build_extensions: {
      "lib/src/vocab/manifest.json": [
        "lib/src/vocab/generated/_index.dart",
        "lib/src/vocab/generated/*.dart"
      ]
    }
    build_to: source
    auto_apply: dependents